/// <reference types="node" />
/**
 * Regenerates `src/core/icons.ts` from Pixelarticons (MIT) at a pinned commit:
 * `bun packages/design/scripts/vendor-icons.ts`. A local one-off that needs the network and a
 * logged-in `gh`; CI only compiles its output. Each SVG is checked against the git blob id GitHub lists for its path at
 * that commit, and only `<path d>` data crosses into the bundle.
 */
import { execFileSync } from "node:child_process"
import { createHash } from "node:crypto"
import { writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const REPO = "halfmage/pixelarticons"
/** Tag v2.4.0. */
const COMMIT = "9e6658cdb790ef03deafdb482867b0cc995b1288"

export const NAMES = [
	"arrow-right",
	"arrows-horizontal",
	"audio-waveform",
	"check",
	"chevron-down",
	"close",
	"coins",
	"copy",
	"download",
	"external-link",
	"eye",
	"eye-off",
	"hourglass",
	"info-box",
	"key",
	"loader",
	"minus",
	"monitor",
	"moon",
	"plus",
	"reload",
	"repeat",
	"save",
	"search",
	"square-alert",
	"sun",
	"tv",
	"upload",
	"wallet",
	"warning-diamond",
	"zap",
] as const

export interface IconPaths {
	viewBox: string
	d: string[]
}

const ROOT_ATTRS = new Set(["xmlns", "width", "height", "fill", "viewBox"])

/** A tag's attributes; throws on any text that is not a double-quoted attribute, or a repeated name. */
function attrs(text: string): Map<string, string> {
	const out = new Map<string, string>()
	const attr = /\s+([a-zA-Z:-]+)="([^"]*)"/y
	let end = 0
	for (let m = attr.exec(text); m; m = attr.exec(text)) {
		if (out.has(m[1])) throw new Error(`repeated attribute: ${m[1]}`)
		out.set(m[1], m[2])
		end = attr.lastIndex
	}
	const rest = text.slice(end).trim()
	if (rest !== "") throw new Error(`unparsed attribute text: ${rest.slice(0, 40)}`)
	return out
}

/**
 * The ordered `d` data of a path-only SVG. Throws on any other element, on a path attribute other
 * than `d`, on a root attribute outside `xmlns/width/height/fill/viewBox`, or on text content.
 */
export function extractPaths(svg: string): IconPaths {
	const root = svg.trim().match(/^<svg\b([^>]*)>([\s\S]*)<\/svg>$/)
	if (!root) throw new Error("not a single <svg> element")
	const rootAttrs = attrs(root[1])
	for (const name of rootAttrs.keys()) if (!ROOT_ATTRS.has(name)) throw new Error(`root attribute not allowed: ${name}`)
	const viewBox = rootAttrs.get("viewBox")
	if (!viewBox || !/^[\d.\s-]+$/.test(viewBox)) throw new Error("missing or non-numeric viewBox")

	const d: string[] = []
	const rest = root[2].replace(/<path\b([^>]*?)\/>/g, (_, inner: string) => {
		const a = attrs(inner)
		if (a.size !== 1 || !a.has("d")) throw new Error(`path attributes not allowed: ${[...a.keys()].join(",")}`)
		const value = a.get("d") ?? ""
		if (!/^[MmLlHhVvZzCcSsQqTtAa\d.,\s-]+$/.test(value)) throw new Error("path data has characters outside the SVG path grammar")
		d.push(value)
		return ""
	})
	if (rest.trim() !== "") throw new Error(`content other than <path/> elements: ${rest.trim().slice(0, 40)}`)
	if (d.length === 0) throw new Error("no paths")
	return { viewBox, d }
}

function gitBlobSha(bytes: Uint8Array): string {
	return createHash("sha1").update(`blob ${bytes.length}\0`).update(bytes).digest("hex")
}

async function main(): Promise<void> {
	// Through `gh`, whose login lifts the anonymous API rate limit shared hosts exhaust.
	const tree = JSON.parse(execFileSync("gh", ["api", `repos/${REPO}/git/trees/${COMMIT}?recursive=1`], { encoding: "utf8" })) as {
		tree: Array<{ path: string; sha: string }>
	}
	const blobs = new Map(tree.tree.map((e) => [e.path, e.sha]))
	const icons: Record<string, IconPaths> = {}
	for (const name of NAMES) {
		const path = `svg/${name}.svg`
		const res = await fetch(`https://raw.githubusercontent.com/${REPO}/${COMMIT}/${path}`)
		if (!res.ok) throw new Error(`${path}: HTTP ${res.status}`)
		const bytes = new Uint8Array(await res.arrayBuffer())
		if (gitBlobSha(bytes) !== blobs.get(path)) throw new Error(`${path}: content does not match the blob at ${COMMIT}`)
		icons[name] = extractPaths(new TextDecoder().decode(bytes))
	}
	const body = Object.entries(icons)
		.map(([name, p]) => `\t"${name}": { viewBox: "${p.viewBox}", d: [${p.d.map((x) => `"${x}"`).join(", ")}] },`)
		.join("\n")
	const out = `// Generated by scripts/vendor-icons.ts from ${REPO} at ${COMMIT} (v2.4.0, MIT; see LICENSE-pixelarticons.txt). Do not edit.
export const ICONS = {
${body}
} as const satisfies Record<string, { viewBox: string; d: readonly string[] }>

export type PixelIconName = keyof typeof ICONS
`
	writeFileSync(join(dirname(fileURLToPath(import.meta.url)), "../src/core/icons.ts"), out)
	console.log(`wrote ${NAMES.length} icons`)
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await main()
