[package]
name = "token_bridge_hub_contract"
authors = ["unleashed"]
compiler_version = ">=1.0.0"
type = "contract"

[dependencies]
token = { git = "https://github.com/AztecProtocol/aztec-standards", tag = "v6.0.0-rc.1", directory = "src/token_contract" }
claim_secret_lib = { path = "../claim_secret" }
register_hash_lib = { path = "../register_hash" }
aztec = { git = "https://github.com/aztec-labs-eng/aztec-nr", tag = "v6.0.0-rc.1", directory = "aztec" }
compressed_string = { git = "https://github.com/aztec-labs-eng/aztec-nr", tag = "v6.0.0-rc.1", directory = "compressed-string" }
token_portal_content_hash_lib = { path = "../token_portal_content_hash_lib" }
